import { ZodiacCard } from './types';

export const ZODIAC_CARDS_DATABASE: Record<string, ZodiacCard> = {
  card_aries_prime: {
    id: 'card_aries_prime',
    sign: 'Aries',
    name: "Ram's Ignition",
    rarity: 'legendary',
    type: 'passive',
    powerTitle: "Ram's Ignition",
    primaryEffect: 'Bomb recharge cooldown recovers 25% faster while actively moving.',
    secondaryEffect: 'Active skill dashes forward with a fiery knockback trail.',
    limitation: 'Takes +6% more damage if standing completely still for over 2 seconds.',
    description: 'Increases bomb recharge recovery by 25% while moving and grants explosive dash speed.',
    synergyElement: 'Fire',
    abilityKey: 'infernal_ram',
    stats: { damageBonus: 4, speedBonus: 10 },
    isUnlocked: true,
  },
  card_taurus_aegis: {
    id: 'card_taurus_aegis',
    sign: 'Taurus',
    name: 'Bastion of the Bull',
    rarity: 'legendary',
    type: 'passive',
    powerTitle: 'Bastion of the Bull',
    primaryEffect: 'Gains +22 Base Armor and complete immunity to blast knockback displacement.',
    secondaryEffect: 'Active skill slams ground, detonating adjacent blocks and repelling enemies.',
    limitation: '-5% Base Sprint Speed (Heavier stance).',
    description: 'Grants +22 Base Armor, +15 Max HP, and immunity to blast knockback displacement.',
    synergyElement: 'Earth',
    abilityKey: 'bastion_bull',
    stats: { armorBonus: 22, hpBonus: 15 },
    isUnlocked: true,
  },
  card_gemini_echo: {
    id: 'card_gemini_echo',
    sign: 'Gemini',
    name: 'Twin Mirage Engine',
    rarity: 'legendary',
    type: 'active',
    powerTitle: 'Twin Mirage Engine',
    primaryEffect: 'Primary bomb drops a secondary micro-spark on an adjacent tile.',
    secondaryEffect: 'Active skill summons an astral decoy that confuses rival bots.',
    limitation: 'Micro-sparks deal 35% less damage than standard bombs.',
    description: 'Grants +1 Starting Bomb Chamber and places dual micro-sparks on bomb detonations.',
    synergyElement: 'Air',
    abilityKey: 'twin_mirage',
    stats: { bombCountBonus: 1 },
    isUnlocked: true,
  },
  card_cancer_carapace: {
    id: 'card_cancer_carapace',
    sign: 'Cancer',
    name: 'Lunar Carapace',
    rarity: 'legendary',
    type: 'passive',
    powerTitle: 'Lunar Carapace',
    primaryEffect: 'Converts 20% of all blast damage taken into a temporary protective shield.',
    secondaryEffect: 'Active skill conjures a tidal ward that blocks the next hit and heals 18 HP.',
    limitation: 'Standard blast damage without elemental item synergy.',
    description: 'Converts 20% of blast damage taken into shields and restores HP upon picking up loot.',
    synergyElement: 'Water',
    abilityKey: 'lunar_carapace',
    stats: { armorBonus: 10, hpBonus: 10 },
    isUnlocked: true,
  },
  card_leo_corona: {
    id: 'card_leo_corona',
    sign: 'Leo',
    name: 'Solar Dominance',
    rarity: 'legendary',
    type: 'passive',
    powerTitle: 'Solar Dominance',
    primaryEffect: 'Deals +15% bonus explosion damage while HP remains above 65%.',
    secondaryEffect: 'Active Solar Roar briefly slows foes and expands bomb radius by +1 for 5s.',
    limitation: 'Bonus damage deactivates when dropped below 65% HP.',
    description: 'Unlocks +15% explosion damage while above 65% HP and expands blast radius on roar.',
    synergyElement: 'Fire',
    abilityKey: 'solar_corona',
    stats: { damageBonus: 8, bombRadiusBonus: 1 },
    isUnlocked: true,
  },
  card_virgo_matrix: {
    id: 'card_virgo_matrix',
    sign: 'Virgo',
    name: 'Calculated Demolition',
    rarity: 'legendary',
    type: 'passive',
    powerTitle: 'Calculated Demolition',
    primaryEffect: 'Destroyed walls guarantee higher tier loot drops and +1 Base Explosion Radius.',
    secondaryEffect: 'Active Matrix Scan pulls all arena loot pickups within 5 tiles directly to you.',
    limitation: 'Requires meticulous spatial bomb planning.',
    description: 'Guarantees higher tier loot drops from destroyed walls and provides +1 Blast Radius.',
    synergyElement: 'Earth',
    abilityKey: 'celestial_precision',
    stats: { bombRadiusBonus: 1, comboDurationBonus: 1.0 },
    isUnlocked: true,
  },
  card_libra_balance: {
    id: 'card_libra_balance',
    sign: 'Libra',
    name: 'Harmonic Equilibrium',
    rarity: 'legendary',
    type: 'passive',
    powerTitle: 'Harmonic Equilibrium',
    primaryEffect: 'While at lower HP % than your opponent, gain +15% move speed and 50% self-damage reduction.',
    secondaryEffect: 'Active pulse deflects active bombs and pushes opponents back.',
    limitation: 'Equilibrium bonus deactivates when ahead in HP %.',
    description: 'Boosts movement speed by +15% and reduces self-blast damage by 50% when at lower HP.',
    synergyElement: 'Air',
    abilityKey: 'scales_justice',
    stats: { speedBonus: 10, comboDurationBonus: 1.2 },
    isUnlocked: true,
  },
  card_scorpio_venom: {
    id: 'card_scorpio_venom',
    sign: 'Scorpio',
    name: 'Venomous Retribution',
    rarity: 'legendary',
    type: 'passive',
    powerTitle: 'Venomous Retribution',
    primaryEffect: 'Explosions leave a toxic zone for 2.2s that slows foes by 22% and inflicts poison.',
    secondaryEffect: 'Active skill plants an instant clandestine trap-bomb with enhanced venom.',
    limitation: '-8 Base Max HP (Lighter assassin chassis).',
    description: 'Explosions leave lingering toxic zones that slow enemies by 22% and inflict damage over time.',
    synergyElement: 'Water',
    abilityKey: 'venom_retribution',
    stats: { damageBonus: 6 },
    isUnlocked: true,
  },
  card_sagittarius_arrow: {
    id: 'card_sagittarius_arrow',
    sign: 'Sagittarius',
    name: 'Celestial Ballista',
    rarity: 'legendary',
    type: 'passive',
    powerTitle: 'Celestial Ballista',
    primaryEffect: 'Explosions travel +1 additional tile along unobstructed corridors.',
    secondaryEffect: 'Active skill fires a piercing celestial bolt that detonates bombs at range.',
    limitation: '-6 Base Armor (Vulnerable in tight quarters).',
    description: 'Explosions travel +1 additional tile through corridors and grants high movement speed.',
    synergyElement: 'Fire',
    abilityKey: 'celestial_ballista',
    stats: { bombRadiusBonus: 1, speedBonus: 12 },
    isUnlocked: true,
  },
  card_capricorn_colossus: {
    id: 'card_capricorn_colossus',
    sign: 'Capricorn',
    name: 'Obsidian Bastion',
    rarity: 'legendary',
    type: 'passive',
    powerTitle: 'Obsidian Bastion',
    primaryEffect: 'Gains +18 Base Armor and permanent resistance to slows and stuns.',
    secondaryEffect: 'Active skill summons 2 obsidian barricades to seal enemy escape routes.',
    limitation: '-4% Base Movement Speed.',
    description: 'Provides +18 Base Armor, complete slow resistance, and creates obsidian roadblocks.',
    synergyElement: 'Earth',
    abilityKey: 'obsidian_titan',
    stats: { armorBonus: 18, hpBonus: 15 },
    isUnlocked: true,
  },
  card_aquarius_vortex: {
    id: 'card_aquarius_vortex',
    sign: 'Aquarius',
    name: 'Cosmic Singularity',
    rarity: 'legendary',
    type: 'passive',
    powerTitle: 'Cosmic Singularity',
    primaryEffect: 'Reduces all cooldowns by 15% and accelerates combo recharge cycles.',
    secondaryEffect: 'Active skill spawns a gravitational vortex pulling bombs and enemies for 2.2s.',
    limitation: 'Vortex can displace the player if positioned carelessly.',
    description: 'Reduces all cooldowns by 15% and creates a gravitational vortex that draws nearby targets.',
    synergyElement: 'Air',
    abilityKey: 'cosmic_singularity',
    stats: { cooldownReduction: 0.15, comboDurationBonus: 1.5 },
    isUnlocked: true,
  },
  card_pisces_dream: {
    id: 'card_pisces_dream',
    sign: 'Pisces',
    name: 'Dreamstride Evasion',
    rarity: 'legendary',
    type: 'passive',
    powerTitle: 'Dreamstride Evasion',
    primaryEffect: 'Active skill turns you ethereal for 2.5s, allowing free passage through destructible blocks.',
    secondaryEffect: 'Gains 1.0s emergency invulnerability and speed boost when dropping below 30% HP.',
    limitation: '-4 Bomb Base Damage (Finesse focused).',
    description: 'Allows wall-phasing mistwalk and grants emergency invulnerability when critically wounded.',
    synergyElement: 'Water',
    abilityKey: 'tidal_mirage',
    stats: { speedBonus: 12 },
    isUnlocked: true,
  },
};
