import { PlayerPath, SpecializationPath, SynergyArchetype } from './types';

export const SPECIALIZATION_PATHS: Record<PlayerPath, SpecializationPath> = {
  bomb_master: {
    id: 'bomb_master',
    name: 'Bomb Master',
    icon: '💣',
    tagline: 'Tactical area denial, precision multi-bombing, and rapid ordinance cycles.',
    difficulty: 3,
    style: 'Tactical / Control',
    primaryAdvantage: '+1 Maximum Bomb Stock Capacity (Start with 2 active bombs).',
    secondaryAdvantage: '+10% Faster chamber recharge pacing.',
    tradeoff: '-3% Base Movement Speed (Heavier bomb harness).',
    powerBudget: {
      offense: 35,
      mobility: 15,
      utility: 35,
      survival: 15,
      total: 100,
    },
    stats: {
      bombCountBonus: 1,
      speedBonus: -6,
    },
  },
  velocity: {
    id: 'velocity',
    name: 'Velocity',
    icon: '⚡',
    tagline: 'High-speed repositioning, aggressive hit-and-run tactics, and swift escapes.',
    difficulty: 4,
    style: 'Aggressive / Mobility',
    primaryAdvantage: '+7% Base Movement Speed (+16 px/s sprint speed).',
    secondaryAdvantage: '+1.5s Extended Combo Duration retention window.',
    tradeoff: '-5 Base Max HP (Lighter kinetic frame).',
    powerBudget: {
      offense: 20,
      mobility: 45,
      utility: 20,
      survival: 15,
      total: 100,
    },
    stats: {
      speedBonus: 16,
      hpBonus: -5,
      comboDurationBonus: 1.5,
    },
  },
  blast_force: {
    id: 'blast_force',
    name: 'Blast Force',
    icon: '💥',
    tagline: 'Colossal explosive radius, massive obstacle destruction, and corridor pressure.',
    difficulty: 3,
    style: 'Area Control / Siege',
    primaryAdvantage: '+1 Blast Radius on all primary ordinance detonations.',
    secondaryAdvantage: '+6 Explosion Damage bonus.',
    tradeoff: '+0.2s Bomb Recharge Pacing (Heavy explosive payload).',
    powerBudget: {
      offense: 45,
      mobility: 15,
      utility: 25,
      survival: 15,
      total: 100,
    },
    stats: {
      bombRadiusBonus: 1,
      damageBonus: 6,
    },
  },
  guardian: {
    id: 'guardian',
    name: 'Guardian',
    icon: '🛡️',
    tagline: 'Fortified resilience, blast damage mitigation, and emergency shielding.',
    difficulty: 2,
    style: 'Survival / Counter',
    primaryAdvantage: '+20 Max HP and +12 Physical Base Armor.',
    secondaryAdvantage: 'Instantly gains +15 Emergency Shield when falling below 35% HP.',
    tradeoff: '-4% Base Movement Speed (Reinforced battle armor).',
    powerBudget: {
      offense: 15,
      mobility: 15,
      utility: 20,
      survival: 50,
      total: 100,
    },
    stats: {
      hpBonus: 20,
      armorBonus: 12,
      speedBonus: -8,
      critShieldPercent: 15,
    },
  },
};

export const SYNERGY_ARCHETYPES: SynergyArchetype[] = [
  {
    id: 'demolition',
    name: 'Demolition Siege',
    icon: '💣💥',
    title: 'Demolition Build',
    style: 'Rapid-fire mass explosive saturation',
    recipe: ['Bomb Master', 'Cooldown Reduction', 'Destruction Bonus'],
    description: 'Deploys continuous barrages of bombs to eradicate walls and corner opponents into unavoidable crossfires.',
    recommendedSigns: ['Gemini', 'Virgo', 'Aquarius'],
    recommendedPath: 'bomb_master',
  },
  {
    id: 'assassin',
    name: 'Astral Assassin',
    icon: '⚡🗡️',
    title: 'Assassin Build',
    style: 'High-speed corner traps and critical strikes',
    recipe: ['Velocity', 'Evasion Movement', 'Adrenaline Burst'],
    description: 'Dashes through danger lanes, cutting off enemy routes and detonating lethal ambushes at maximum sprint velocity.',
    recommendedSigns: ['Aries', 'Scorpio', 'Sagittarius', 'Pisces'],
    recommendedPath: 'velocity',
  },
  {
    id: 'fortress',
    name: 'Cosmic Fortress',
    icon: '🛡️🏰',
    title: 'Fortress Build',
    style: 'Unshakable bastion and counter-attacks',
    recipe: ['Guardian', 'Armor Bastion', 'Shield Overcharge'],
    description: 'Withstands close-range blasts with impenetrable defenses, turning rival aggression into catastrophic counter-blows.',
    recommendedSigns: ['Taurus', 'Cancer', 'Capricorn'],
    recommendedPath: 'guardian',
  },
  {
    id: 'zone_denial',
    name: 'Zone Denial Control',
    icon: '💥☣️',
    title: 'Zone Denial Build',
    style: 'Corridor lockdown and lingering hazards',
    recipe: ['Blast Force', 'Area Control', 'Toxic / Lingering Effects'],
    description: 'Chokes entire map sectors with wide-reach explosions and environmental hazards, leaving enemies nowhere to run.',
    recommendedSigns: ['Scorpio', 'Leo', 'Virgo', 'Aquarius'],
    recommendedPath: 'blast_force',
  },
  {
    id: 'long_sniper',
    name: 'Celestial Sniper',
    icon: '♐🎯',
    title: 'Sniper Build',
    style: 'Long-corridor piercing shots and line of sight control',
    recipe: ['Velocity or Blast Force', 'Corridor Extension', 'Speed Bonus'],
    description: 'Eliminates foes from extreme distance down linear pathways while easily outrunning return ordinance.',
    recommendedSigns: ['Sagittarius', 'Aries', 'Libra'],
    recommendedPath: 'velocity',
  },
  {
    id: 'ethereal_trickster',
    name: 'Ethereal Phaser',
    icon: '♓✨',
    title: 'Phaser Build',
    style: 'Wall-phasing and invulnerability resets',
    recipe: ['Velocity or Guardian', 'Mistwalk Phasing', 'Decoy Misdirection'],
    description: 'Bypasses solid obstacles with ease, escaping tight dead-ends and appearing unexpectedly behind opponents.',
    recommendedSigns: ['Pisces', 'Gemini', 'Cancer', 'Libra'],
    recommendedPath: 'velocity',
  },
];
