import { ElementType, ZodiacInfo, ZodiacSign } from './types';

export const ZODIAC_SIGNS: Record<ZodiacSign, ZodiacInfo> = {
  Aries: {
    sign: 'Aries',
    name: 'Aries (The Ram)',
    symbol: '♈',
    element: 'Fire',
    dateRange: 'Mar 21 - Apr 19',
    themeColor: '#EF4444',
    accentColor: '#F87171',
    description: 'Relentless vanguard who charges forward with fiery momentum and explosive velocity.',
    rarity: 'legendary',
    powerTitle: "Ram's Ignition",
    primaryEffect: 'Bomb recharge cooldown recovers 25% faster while actively moving.',
    secondaryEffect: 'Active skill dashes forward with a fiery knockback trail.',
    limitation: 'Takes +6% more damage if standing completely still for over 2 seconds.',
    keyStats: [
      '+25% Move-Action Bomb Pacing',
      'Dash Impact: 11.0s Cooldown',
      'Sprint Base: 228 px/s',
      'Vulnerability when stationary',
    ],
    playstyle: 'Rushdown Breaker',
    passiveName: "Ram's Ignition",
    passiveDesc: 'Cooldown of bomb placement recovers 25% faster when continuously moving.',
    activeName: 'Meteor Rush',
    activeDesc: 'Dash forward instantly leaving an explosive blast trail and knocking obstacles aside.',
    activeCooldown: 11.0,
    powerBudget: {
      offense: 30,
      mobility: 35,
      utility: 20,
      survival: 15,
      total: 100,
    },
    baseHp: 96,
    baseSpeed: 228,
    baseArmor: 10,
    baseBombCount: 1,
    baseBombRadius: 2,
    baseBombDamage: 50,
  },
  Taurus: {
    sign: 'Taurus',
    name: 'Taurus (The Bull)',
    symbol: '♉',
    element: 'Earth',
    dateRange: 'Apr 20 - May 20',
    themeColor: '#10B981',
    accentColor: '#34D399',
    description: 'Steadfast juggernaut with massive physical resilience and map-quaking impacts.',
    rarity: 'legendary',
    powerTitle: 'Bastion of the Bull',
    primaryEffect: 'Gains +22 Base Armor and complete immunity to blast knockback displacement.',
    secondaryEffect: 'Active skill slams ground, detonating adjacent blocks and repelling enemies.',
    limitation: '-5% Base Sprint Speed (Heavier stance).',
    keyStats: [
      '+22 Base Physical Armor',
      'Immune to blast knockback',
      'Seismic Stomp: 12.5s Cooldown',
      'Base Speed: 200 px/s (-5%)',
    ],
    playstyle: 'Fortress Juggernaut',
    passiveName: 'Granite Skin',
    passiveDesc: 'Takes 15% reduced blast damage and is immune to explosion displacement.',
    activeName: 'Seismic Shockwave',
    activeDesc: 'Stomp the ground creating an earthquake that detonates all adjacent blocks and repels foes.',
    activeCooldown: 12.5,
    powerBudget: {
      offense: 15,
      mobility: 15,
      utility: 20,
      survival: 50,
      total: 100,
    },
    baseHp: 115,
    baseSpeed: 200,
    baseArmor: 22,
    baseBombCount: 1,
    baseBombRadius: 2,
    baseBombDamage: 48,
  },
  Gemini: {
    sign: 'Gemini',
    name: 'Gemini (The Twins)',
    symbol: '♊',
    element: 'Air',
    dateRange: 'May 21 - Jun 20',
    themeColor: '#F59E0B',
    accentColor: '#FBBF24',
    description: 'Unpredictable trickster capable of dual chambering and deploying spectral decoys.',
    rarity: 'legendary',
    powerTitle: 'Twin Mirage Engine',
    primaryEffect: 'Primary bomb drops a secondary micro-spark on an adjacent tile.',
    secondaryEffect: 'Active skill summons an astral decoy that confuses rival bots.',
    limitation: 'Micro-sparks deal 35% less damage than standard bombs.',
    keyStats: [
      '+1 Extra Starting Bomb Chamber',
      'Dual Micro-Spark Placement',
      'Decoy Mirror: 11.5s Cooldown',
      'Lighter Armor Baseline: 8',
    ],
    playstyle: 'Trickster Area Control',
    passiveName: 'Twin Sparks',
    passiveDesc: 'Starts the match with +1 Max Bomb capacity and faster bomb reload.',
    activeName: 'Astral Decoy',
    activeDesc: 'Summons a mirror illusion that confuses enemy bots and drops an instant secondary micro-bomb.',
    activeCooldown: 11.5,
    powerBudget: {
      offense: 35,
      mobility: 25,
      utility: 30,
      survival: 10,
      total: 100,
    },
    baseHp: 92,
    baseSpeed: 220,
    baseArmor: 8,
    baseBombCount: 2,
    baseBombRadius: 2,
    baseBombDamage: 45,
  },
  Cancer: {
    sign: 'Cancer',
    name: 'Cancer (The Crab)',
    symbol: '♋',
    element: 'Water',
    dateRange: 'Jun 21 - Jul 22',
    themeColor: '#06B6D4',
    accentColor: '#22D3EE',
    description: 'Protective tide-guardian who turns defensive parries into restorative momentum.',
    rarity: 'legendary',
    powerTitle: 'Lunar Carapace',
    primaryEffect: 'Converts 20% of all blast damage taken into a temporary protective shield.',
    secondaryEffect: 'Active skill conjures a tidal ward that blocks the next hit and heals 18 HP.',
    limitation: 'Standard blast damage without elemental item synergy.',
    keyStats: [
      '+20% Damage-to-Shield Conversion',
      'Tidal Ward: 13.0s Cooldown',
      'Loot pickup grants +8 Shield',
      'Balanced Vitality: 105 HP',
    ],
    playstyle: 'Defensive Sustain',
    passiveName: 'Tidal Carapace',
    passiveDesc: 'Picking up loot shields for 8 HP (up to 24 max shield).',
    activeName: 'Lunar Ward',
    activeDesc: 'Conjures a protective water barrier that negates the next blast and restores 18 HP.',
    activeCooldown: 13.0,
    powerBudget: {
      offense: 15,
      mobility: 15,
      utility: 30,
      survival: 40,
      total: 100,
    },
    baseHp: 105,
    baseSpeed: 208,
    baseArmor: 16,
    baseBombCount: 1,
    baseBombRadius: 2,
    baseBombDamage: 47,
  },
  Leo: {
    sign: 'Leo',
    name: 'Leo (The Lion)',
    symbol: '♌',
    element: 'Fire',
    dateRange: 'Jul 23 - Aug 22',
    themeColor: '#EAB308',
    accentColor: '#FDE047',
    description: 'Radiant leader dominating the arena with blinding solar blasts and high-confidence buffs.',
    rarity: 'legendary',
    powerTitle: 'Solar Dominance',
    primaryEffect: 'Deals +15% bonus explosion damage while HP remains above 65%.',
    secondaryEffect: 'Active Solar Roar briefly slows foes and expands bomb radius by +1 for 5s.',
    limitation: 'Bonus damage deactivates when dropped below 65% HP.',
    keyStats: [
      '+15% High-HP Damage Buff',
      'Solar Roar: 12.0s Cooldown',
      'Base Bomb Damage: 54',
      'Requires proactive tempo',
    ],
    playstyle: 'Dominator Pressure',
    passiveName: 'Solar Dominance',
    passiveDesc: 'Deals 15% bonus damage with explosions while HP is above 65%.',
    activeName: 'Solar Roar',
    activeDesc: 'Releases a blinding burst of solar energy that briefly slows enemies and expands bomb blast radius by +1 for 5s.',
    activeCooldown: 12.0,
    powerBudget: {
      offense: 40,
      mobility: 20,
      utility: 25,
      survival: 15,
      total: 100,
    },
    baseHp: 100,
    baseSpeed: 216,
    baseArmor: 12,
    baseBombCount: 1,
    baseBombRadius: 2,
    baseBombDamage: 54,
  },
  Virgo: {
    sign: 'Virgo',
    name: 'Virgo (The Maiden)',
    symbol: '♍',
    element: 'Earth',
    dateRange: 'Aug 23 - Sep 22',
    themeColor: '#84CC16',
    accentColor: '#A3E635',
    description: 'Methodical strategist calculating optimal paths, maximum loot yield, and pinpoint blasts.',
    rarity: 'legendary',
    powerTitle: 'Calculated Demolition',
    primaryEffect: 'Destroyed walls guarantee higher tier loot drops and +1 Base Explosion Radius.',
    secondaryEffect: 'Active Matrix Scan pulls all arena loot pickups within 5 tiles directly to you.',
    limitation: 'Requires meticulous spatial bomb planning.',
    keyStats: [
      '+1 Base Explosion Radius (3 Tiles)',
      'High-Tier Loot Drop Guarantee',
      'Matrix Vacuum: 9.5s Cooldown',
      'Precise Resource Management',
    ],
    playstyle: 'Precision Tactician',
    passiveName: 'Calculated Demolition',
    passiveDesc: 'Destroyed walls guarantee higher tier loot and +1 base explosion radius.',
    activeName: 'Matrix Scan',
    activeDesc: 'Scans the arena, instantly pulling all active loot pickups in a 5-tile radius directly to you and granting 8 armor.',
    activeCooldown: 9.5,
    powerBudget: {
      offense: 25,
      mobility: 20,
      utility: 40,
      survival: 15,
      total: 100,
    },
    baseHp: 96,
    baseSpeed: 212,
    baseArmor: 12,
    baseBombCount: 1,
    baseBombRadius: 3,
    baseBombDamage: 48,
  },
  Libra: {
    sign: 'Libra',
    name: 'Libra (The Scales)',
    symbol: '♎',
    element: 'Air',
    dateRange: 'Sep 23 - Oct 22',
    themeColor: '#38BDF8',
    accentColor: '#7DD3FC',
    description: 'Harmonious duelist balancing offensive power with kinetic equilibrium and counter-attacks.',
    rarity: 'legendary',
    powerTitle: 'Harmonic Equilibrium',
    primaryEffect: 'While at lower HP % than your opponent, gain +15% move speed and 50% self-damage reduction.',
    secondaryEffect: 'Active pulse deflects active bombs and pushes opponents back.',
    limitation: 'Equilibrium bonus deactivates when ahead in HP %.',
    keyStats: [
      '+15% Comeback Speed Boost',
      '50% Self-Blast Protection',
      'Deflection Pulse: 9.0s Cooldown',
      'Extended +1.2s Combo Window',
    ],
    playstyle: 'Balanced Skirmisher',
    passiveName: 'Harmonic Equilibrium',
    passiveDesc: 'Combo window stays active 1.2s longer; self-blasts deal 50% less damage.',
    activeName: 'Equilibrium Field',
    activeDesc: 'Emits a kinetic pulse that deflects nearby active bombs away from you and pushes opponents back.',
    activeCooldown: 9.0,
    powerBudget: {
      offense: 25,
      mobility: 30,
      utility: 25,
      survival: 20,
      total: 100,
    },
    baseHp: 100,
    baseSpeed: 216,
    baseArmor: 14,
    baseBombCount: 1,
    baseBombRadius: 2,
    baseBombDamage: 49,
  },
  Scorpio: {
    sign: 'Scorpio',
    name: 'Scorpio (The Scorpion)',
    symbol: '♏',
    element: 'Water',
    dateRange: 'Oct 23 - Nov 21',
    themeColor: '#9333EA',
    accentColor: '#C084FC',
    description: 'Lethal ambush predator infusing explosives with toxic venom and punishment mechanics.',
    rarity: 'legendary',
    powerTitle: 'Venomous Retribution',
    primaryEffect: 'Explosions leave a toxic zone for 2.2s that slows foes by 22% and inflicts poison.',
    secondaryEffect: 'Active skill plants an instant clandestine trap-bomb with enhanced venom.',
    limitation: '-8 Base Max HP (Lighter assassin chassis).',
    keyStats: [
      'Lingering Toxic Mist (2.2s)',
      'Death Stinger Trap: 11.0s Cooldown',
      '22% Opponent Venom Slow',
      'Fragile Base: 92 HP',
    ],
    playstyle: 'Ambush Assassin',
    passiveName: 'Venom Infusion',
    passiveDesc: 'Explosions inflict Venom, dealing 14 poison damage over 2.5 seconds and slowing movement by 22%.',
    activeName: 'Death Stinger',
    activeDesc: 'Plants an instant clandestine trap-bomb that detonates with double venom intensity when an enemy draws near.',
    activeCooldown: 11.0,
    powerBudget: {
      offense: 35,
      mobility: 20,
      utility: 35,
      survival: 10,
      total: 100,
    },
    baseHp: 92,
    baseSpeed: 224,
    baseArmor: 10,
    baseBombCount: 1,
    baseBombRadius: 2,
    baseBombDamage: 50,
  },
  Sagittarius: {
    sign: 'Sagittarius',
    name: 'Sagittarius (The Archer)',
    symbol: '♐',
    element: 'Fire',
    dateRange: 'Nov 22 - Dec 21',
    themeColor: '#FB923C',
    accentColor: '#FDBA74',
    description: 'Long-range vanguard moving with high velocity and projecting fiery celestial arrows.',
    rarity: 'legendary',
    powerTitle: 'Celestial Ballista',
    primaryEffect: 'Explosions travel +1 additional tile along unobstructed corridors.',
    secondaryEffect: 'Active skill fires a piercing celestial bolt that detonates bombs at range.',
    limitation: '-6 Base Armor (Vulnerable in tight quarters).',
    keyStats: [
      '+1 Corridor Blast Extension',
      'Starfire Arrow: 9.5s Cooldown',
      'Native Sprint: 232 px/s',
      'Lighter Defense: 8 Armor',
    ],
    playstyle: 'High-Speed Sniper',
    passiveName: 'Centaur Agility',
    passiveDesc: 'Highest native movement speed (+8% base speed) and fast obstacle clearance.',
    activeName: 'Starfire Arrow',
    activeDesc: 'Fires a high-speed piercing celestial bolt in target direction that shatters walls and triggers bombs immediately.',
    activeCooldown: 9.5,
    powerBudget: {
      offense: 35,
      mobility: 35,
      utility: 20,
      survival: 10,
      total: 100,
    },
    baseHp: 95,
    baseSpeed: 232,
    baseArmor: 8,
    baseBombCount: 1,
    baseBombRadius: 2,
    baseBombDamage: 50,
  },
  Capricorn: {
    sign: 'Capricorn',
    name: 'Capricorn (The Sea-Goat)',
    symbol: '♑',
    element: 'Earth',
    dateRange: 'Dec 22 - Jan 19',
    themeColor: '#475569',
    accentColor: '#94A3B8',
    description: 'Unyielding architect creating indestructible barricades and turning defense into victory.',
    rarity: 'legendary',
    powerTitle: 'Obsidian Bastion',
    primaryEffect: 'Gains +18 Base Armor and permanent resistance to slows and stuns.',
    secondaryEffect: 'Active skill summons 2 obsidian barricades to seal enemy escape routes.',
    limitation: '-4% Base Movement Speed.',
    keyStats: [
      '+18 Base Physical Armor',
      'Obsidian Barricades: 12.0s Cooldown',
      'Permanent Slow Resistance',
      'Base Speed: 202 px/s',
    ],
    playstyle: 'Tactical Bastion',
    passiveName: 'Mountain Resolve',
    passiveDesc: 'Cannot be stunned or slowed. Gains +4 Armor for every destroyed wall nearby for 6s.',
    activeName: 'Obsidian Wall',
    activeDesc: 'Summons 2 temporary reinforced monoliths directly beside you, sealing off escape routes for foes.',
    activeCooldown: 12.0,
    powerBudget: {
      offense: 20,
      mobility: 15,
      utility: 25,
      survival: 40,
      total: 100,
    },
    baseHp: 112,
    baseSpeed: 202,
    baseArmor: 18,
    baseBombCount: 1,
    baseBombRadius: 2,
    baseBombDamage: 48,
  },
  Aquarius: {
    sign: 'Aquarius',
    name: 'Aquarius (The Water-Bearer)',
    symbol: '♒',
    element: 'Air',
    dateRange: 'Jan 20 - Feb 18',
    themeColor: '#3B82F6',
    accentColor: '#60A5FA',
    description: 'Futuristic innovator manipulating gravitational forces and chaotic cosmic energy.',
    rarity: 'legendary',
    powerTitle: 'Cosmic Singularity',
    primaryEffect: 'Reduces all cooldowns by 15% and accelerates combo recharge cycles.',
    secondaryEffect: 'Active skill spawns a gravitational vortex pulling bombs and enemies for 2.2s.',
    limitation: 'Vortex can displace the player if positioned carelessly.',
    keyStats: [
      '+15% Global Cooldown Reduction',
      'Gravitational Vortex: 12.0s Cooldown',
      'High Combo Synergy',
      'Demands precise timing',
    ],
    playstyle: 'Gravity Controller',
    passiveName: 'Cosmic Resonance',
    passiveDesc: 'Combos provide +15% movement speed and accelerate ability cooldown timers.',
    activeName: 'Gravitational Singularity',
    activeDesc: 'Spawns a micro black-hole vortex that draws all nearby bombs and enemies toward its epicenter for 2.2s.',
    activeCooldown: 12.0,
    powerBudget: {
      offense: 25,
      mobility: 20,
      utility: 40,
      survival: 15,
      total: 100,
    },
    baseHp: 96,
    baseSpeed: 216,
    baseArmor: 12,
    baseBombCount: 1,
    baseBombRadius: 2,
    baseBombDamage: 48,
  },
  Pisces: {
    sign: 'Pisces',
    name: 'Pisces (The Fish)',
    symbol: '♓',
    element: 'Water',
    dateRange: 'Feb 19 - Mar 20',
    themeColor: '#14B8A6',
    accentColor: '#2DD4BF',
    description: 'Mystical illusionist capable of phasing directly through walls and slipping out of traps.',
    rarity: 'legendary',
    powerTitle: 'Dreamstride Evasion',
    primaryEffect: 'Active skill turns you ethereal for 2.5s, allowing free passage through destructible blocks.',
    secondaryEffect: 'Gains 1.0s emergency invulnerability and speed boost when dropping below 30% HP.',
    limitation: '-4 Bomb Base Damage (Finesse focused).',
    keyStats: [
      'Wall-Phasing Mistwalk: 11.5s Cooldown',
      'Critical HP 1.0s Evasion Surge',
      'Agile Baseline: 222 px/s',
      'Base Bomb Damage: 46',
    ],
    playstyle: 'Ethereal Phaser',
    passiveName: 'Dreamstride',
    passiveDesc: 'When entering critical health (below 30% HP), immediately gains 1.0s invulnerability and a burst of speed.',
    activeName: 'Mist Form',
    activeDesc: 'Becomes ethereal for 2.5s: passes freely through destructible walls and gains +25% movement speed.',
    activeCooldown: 11.5,
    powerBudget: {
      offense: 15,
      mobility: 40,
      utility: 25,
      survival: 20,
      total: 100,
    },
    baseHp: 95,
    baseSpeed: 222,
    baseArmor: 10,
    baseBombCount: 1,
    baseBombRadius: 2,
    baseBombDamage: 46,
  },
};

export const ELEMENT_COLORS: Record<ElementType, { primary: string; bg: string; border: string }> = {
  Fire: { primary: '#EF4444', bg: 'rgba(239, 68, 68, 0.15)', border: 'rgba(239, 68, 68, 0.4)' },
  Earth: { primary: '#10B981', bg: 'rgba(16, 185, 129, 0.15)', border: 'rgba(16, 185, 129, 0.4)' },
  Air: { primary: '#38BDF8', bg: 'rgba(56, 189, 248, 0.15)', border: 'rgba(56, 189, 248, 0.4)' },
  Water: { primary: '#06B6D4', bg: 'rgba(6, 182, 212, 0.15)', border: 'rgba(6, 182, 212, 0.4)' },
};

/**
 * Calculates the exact astrological zodiac sign from month (1-12) and day (1-31).
 */
export function getZodiacSignFromDate(month: number, day: number): ZodiacSign {
  if ((month === 3 && day >= 21) || (month === 4 && day <= 19)) return 'Aries';
  if ((month === 4 && day >= 20) || (month === 5 && day <= 20)) return 'Taurus';
  if ((month === 5 && day >= 21) || (month === 6 && day <= 20)) return 'Gemini';
  if ((month === 6 && day >= 21) || (month === 7 && day <= 22)) return 'Cancer';
  if ((month === 7 && day >= 23) || (month === 8 && day <= 22)) return 'Leo';
  if ((month === 8 && day >= 23) || (month === 9 && day <= 22)) return 'Virgo';
  if ((month === 9 && day >= 23) || (month === 10 && day <= 22)) return 'Libra';
  if ((month === 10 && day >= 23) || (month === 11 && day <= 21)) return 'Scorpio';
  if ((month === 11 && day >= 22) || (month === 12 && day <= 21)) return 'Sagittarius';
  if ((month === 12 && day >= 22) || (month === 1 && day <= 19)) return 'Capricorn';
  if ((month === 1 && day >= 20) || (month === 2 && day <= 18)) return 'Aquarius';
  return 'Pisces';
}

export function parseBirthDateToZodiac(dateStr: string): { sign: ZodiacSign; info: ZodiacInfo } {
  const parts = dateStr.split('-');
  if (parts.length === 3) {
    const month = parseInt(parts[1], 10);
    const day = parseInt(parts[2], 10);
    if (!isNaN(month) && !isNaN(day)) {
      const sign = getZodiacSignFromDate(month, day);
      return { sign, info: ZODIAC_SIGNS[sign] };
    }
  }
  return { sign: 'Aries', info: ZODIAC_SIGNS['Aries'] };
}
